name: Build and Push
on:
  push:
    branches: [ master ] # или main, смотря какая у тебя

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo "Starting CI process..."
      - name: Check if index.html exists
        run: ls dashboard/index.html
